spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:56377/restful
    username: restful
    password:

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true



logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace