server:
  port: 8888



spring:
  application:
    name: RESTful

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:53277/restful
    username: restful
    password:



logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: info
