spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql9:3306/restful?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: restful
    password:



springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false



logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: info
