CREATE TABLE USER_TBL (
    ID VARCHAR2(10) PRIMARY KEY,
    PASSWORD VARCHAR2(50) NOT NULL,
    NICKNAME VARCHAR2(30) NULL,
    ADDRESS VARCHAR2(500) NULL,
    PHONE VARCHAR2(15) NULL,
    EMAIL VARCHAR2(320) NULL,
    AVATAR LONG NULL
);